language: node_js
node_js: '12'

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.15.2
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn install lerna -g

install:
  - yarn --frozen-lockfile --non-interactive

stages:
  - name: test
    if: (tag IS blank) OR (type != push) OR (repo != damylen/csnext)
  - name: deploy
    if: (tag IS present) AND (type = push) AND (repo = damylen/csnext)

jobs:
  include:
    - stage: test
      name: 'Test'
      script:
        - yarn
        - yarn build
        - yarn test

    - stage: deploy
      script:
        - yarn
        - yarn build
      deploy:
        - provider: script
          script: bash scripts/deploy.sh
          skip_cleanup: true
          on:
            repo: damylen/csnext
            tags: true
        # - provider: releases
        #   api_key: $GITHUB_API_KEY
        #   file: "release/vuetify-${TRAVIS_TAG}.zip"
        #   skip_cleanup: true
        #   on:
        #     repo: damylen/csnext
        #     tags: true