# This is a basic workflow to help you get started with Actions
name: build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: 
      - master
      - dev      
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
          node-version: 14
    - run: npm install
    - run: npm run build
    - name: Authenticate with Registry
      run: |
        yarn logout
        echo "registry=http://registry.npmjs.org/" >> .npmrc
        echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
        npm whoami
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    - run: git update-index --assume-unchanged .npmrc
    - run: git update-index --assume-unchanged package.json
    - run: rm package-lock.json
    - run: rm yarn.lock
    - run: npm view @csnext/cs-client versions  --json
      name: View all published @csnext versions
    - run: npm run publish:beta
    - run: npm run publish:release
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
