export enum PropertyValueType {    
    boolean = 'boolean',
    date = 'date',
    datetime = 'datetime',    
    number = 'number',    
    string = 'string',
    time = 'time',
    year = 'year',
    yearmonth = 'yearmonth',
    relation = 'relation',
    url = 'url',
    options = 'options',
    element = "element",
    elementarray = 'elementarray',    
    listitem = 'listitem',
    image = 'image',
    epoch = 'epoch',
    wkt = 'wkt',
    feature = "feature",
    featurecollection = "featurecollection",
    tags = 'tags',
    json = 'json',
    document = 'document',
    meta = 'meta',
    metalist = 'metalist'

}